apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-one-kubeconfig
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: test-one-kubeconfig
    creationPolicy: Owner
  data:
    - secretKey: value.yaml
      remoteRef:
        key: test-one-kubeconfig
